title: The Flounder
description: >-
  TODO Description.
plugins:
  - jekyll-feed

# HTML Compression
compress_html:
  blanklines: false
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  profile: false
  startings: []

# RSS
feed:
  collections:
    issues:
      path: "/issues.xml"

# Custom Directory Structure
collections:
  issues:
    output: true
    permalink: /:year/:month/
  articles:
    output: true
    permalink: /:year/:month/:title/

# Contacts
email: thefloundernews@gmail.com
github_username: floundernews
instagram_username: floundernews
