title: "The Flounder"
description: "Flounder News, Mackenzie's source for everything dull and factual."
logo: "/assets/img/logo.png"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

social:
  links:
    - https://instagram.com/wlmac.floundernews
    - https://facebook.com/macfloundernews

copyright: "&copy; 2020 The Flounder. All Rights Reserved."

subscribe_url: "https://forms.gle/3bvsntMzJKumC4vJ8"

collections:
  articles:
    output: true
    permalink: /:year/:month/:title/
  issues:
    output: true
    permalink: /:year/:month/
  entertainment:
    output: true
    permalink: /fun/:name/
  bios:
    output: true
    permalink: /bios/:name/

compress_html:
  blanklines: false
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  profile: false
  startings: []

externals:
  email: thefloundernews@gmail.com
  github: floundernews
  instagram: wlmac.floundernews
  facebook: macfloundernews

feed:
  collections:
    issues:
      path: "/issues.xml"

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/logo.png"

exclude:
  - assets/js/tsconfig.json
  - assets/js/*.ts
