title: The Flounder
description: >-
  TODO Description.
plugins:
  - jekyll-feed
  - jekyll-paginate

# Custom Directory Structure
collections:
  issues:
    output: true
    permalink: /:year/:month/
  articles:
    output: true
    permalink: /:year/:month/:title/

# Contacts
email: thefloundernews@gmail.com
github_username: floundernews
instagram_username: floundernews
