title: The Flounder
email: thefloundernews@gmail.com
description: >-
  TODO Description.
permalink: /:year/:month/:title/
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/:num/"

# Social media accounts
github_username: floundernews
instagram_username: floundernews
